### ISSUE TITLE
Joining the OpenLayers project

### ISSUE THREAD

**Issue by jahow** [hanreev/types-ol#11]
Hi!

During these past days @KaiVolland and I have been taking a close look at the work that has been done in this repo, and it is impressive to say the least.

The `beta` branch is almost able to fully generate the definition files for the version 6 of the library out of the box, without manual intervention. We have come up with a few improvements to make this generation error-free but are not entirely there yet.

Would the maintainer(s) of this repo agree to collaborate with contributors of the OpenLayers project in order to make this generation completely automatic and integrate it into the publishing workflow of the library? This would mean that eventually this repo would join the OpenLayers organization on Github and become a direct dependency of https://github.com/openlayers/openlayers.

Thanks a lot and again, congratulations on the work accomplished.

**Comment by jahow** [comment]
More specifically, we're having issues with generic types as used here for example:
https://github.com/openlayers/openlayers/blob/b40709ea5b691b281884e7945847fb118725fe70/src/ol/renderer/canvas/Layer.js#L14

This outputs something like this:
```ts
export default class CanvasLayerRenderer<{module:ol/layer/Layer~Layer LayerType}> extends LayerRenderer<{module:ol/layer/Layer~Layer LayerType}> {
```

Which is invalid of course. @hanreev do you have any idea how to make JSDoc better handle generic types in class inheritance? Thanks.

**Comment by hanreev** [comment]
@jahow we need a better `@template` tag parser to solve generic types issues. i'm working on an alternative parser which that hasn't finished yet. See
[https://github.com/hanreev/types-ol/blob/master/jsdoc/plugins/template.js](https://github.com/hanreev/types-ol/blob/master/jsdoc/plugins/template.js)

**Comment by panchitoboy** [comment]
Great job guys!!
