### ISSUE TITLE
Make coordinate a tuple

### ISSUE THREAD

**Issue by 9oelM** [hanreev/types-ol#12]
Coordinate only contains two numbers always. Therefore I think `[number, number]` would be a more accurate representation.

https://github.com/hanreev/types-ol/blob/7c3361a755953d56644545c47c7c9a84faaba62d/%40types/ol/coordinate.d.ts#L3

**Comment by hanreev** [comment]
@9oelM good point. thanks
I think `ol/extent.Extent` also must be represented as `[number, number, number, number]` insteadof `number[]`

**Comment by hanreev** [comment]
I recently discovered that the coordinate can contain 2, 3 or 4 numbers.
- `[x, y]`
- `[x, y, z]`
- `[x, y, z, m]`
