### ISSUE TITLE
error TS2688: missing index.d.js files in subdirectories

### ISSUE THREAD

**Issue by ejn** [hanreev/types-ol#13]
Using @hanreev/types-ol 3.0.0 for OL 6 and `node_modules/@hanreev/types-ol` in my `typeRoots` I'm getting the following errors:
```
error TS2688: Cannot find type definition file for 'control'.

error TS2688: Cannot find type definition file for 'extent'.

error TS2688: Cannot find type definition file for 'format'.

error TS2688: Cannot find type definition file for 'geom'.

error TS2688: Cannot find type definition file for 'interaction'.

error TS2688: Cannot find type definition file for 'layer'.

error TS2688: Cannot find type definition file for 'pointer'.

error TS2688: Cannot find type definition file for 'proj'.

error TS2688: Cannot find type definition file for 'render'.

error TS2688: Cannot find type definition file for 'renderer'.

error TS2688: Cannot find type definition file for 'reproj'.

error TS2688: Cannot find type definition file for 'source'.

error TS2688: Cannot find type definition file for 'structs'.

error TS2688: Cannot find type definition file for 'style'.

error TS2688: Cannot find type definition file for 'tilegrid'.

error TS2688: Cannot find type definition file for 'vec'.

error TS2688: Cannot find type definition file for 'webgl'.
```

These are all the subdirectories of `ol`, none of which contain an `index.d.ts` file, which [is necessary according to TypeScript#27956](https://github.com/microsoft/TypeScript/issues/27956)

According to the [ticket comments](https://github.com/microsoft/TypeScript/issues/27956#issuecomment-536538846), it would be sufficient to have an empty `index.d.ts` in each directory to suppress the error. Would it be possible to include this (or a "proper" solution), or is there some way to work around this error?

**Comment by hanreev** [comment]
@ejn `typeRoots` are intended for global type definitions only.
You need to use `paths` options or install `@hanreev/types-ol` as `@types/ol`. See [here](https://github.com/hanreev/types-ol#usage)

`index.d.ts` in subdirectories is no longer needed because there is already `.d.ts` file with the same name.

**Comment by ejn** [comment]
Using `@types/ol` it was no problem, so I'm assuming it was my mistake somewhere. Thanks @hanreev for your great work!
