### ISSUE TITLE
Missing typings for options in sources.

### ISSUE THREAD

**Issue by bvx89** [hanreev/types-ol#15]
Hi. I've discovered that there are missing typings in the options for the VectorSource class.

The options passed in to the constructor of [VectorSource](@types/ol/source/Vector.d.ts) are also passed in to the [Source](@types/ol/source/Source.d.ts) class in the form of prototypical inheritence, so the VectorSource options should extend the Source options.

I assume that this should probably be done for the other option interfaces as well in the source folder.

**Comment by hanreev** [comment]
@bvx89 there are only two options passed to `ol/source/Source~Source` from `ol/source/Vector~VectorSource`; `attributions` and `wrapX` ([source](https://github.com/openlayers/openlayers/blob/af9f26b9d343e5496ea44a729265c4002616b240/src/ol/source/Vector.js#L170)) with some specific default options.
The other `ol/source/Source~Source` child class will pass its specific default options, thats why `ol/source/Source.Options` inheritance is not needed.
