### ISSUE TITLE
GeometryType export missing in geom.d.ts

### ISSUE THREAD

**Issue by jmacura** [hanreev/types-ol#16]
Hi,

first of all, thank you very much for this package!

I was trying to add the types into my TS project based on OpenLayers and I get following error:
![image](https://user-images.githubusercontent.com/5598693/85386776-4cda4d00-b544-11ea-818f-3112664c41da.png)

where it is imported as follows:
![image](https://user-images.githubusercontent.com/5598693/85386418-e2291180-b543-11ea-934c-6f2ef5758bfd.png)

This seems to be caused by missing line
`export { deafult as GeometryType } from './geom/GeometryType';`
in @type/ol/geom.d.ts file

**Comment by hanreev** [comment]
The `GeometryType` is not exported from `ol/geom` module in the [JS source](https://github.com/openlayers/openlayers/blob/v6.3.1/src/ol/geom.js), so the type definition must reflect that.

You must import it directly from `ol/geom/GeometryType`.
```typescript
import GeometryType from ol/geom/GeometryType;
```

**Comment by jmacura** [comment]
Thanks for pointing that out.
