### ISSUE TITLE
Package downloading as symbolic link

### ISSUE THREAD

**Issue by jt-helsinki** [hanreev/types-ol#2]
Mac OS X
NPM: 6.4.1
Types-ol: 2.0.1

Running `npm i -D @hanreev/types-ol` sees only a broken symbolic inside the package contents

**Comment by hanreev** [comment]
I could not reproduce the issue. I've tried installing it with `npm` and `yarn` without caches and the package is fine.

Tested on:
- macOS 10.14.4 | npm 6.9.0 | yarn 1.16.0
- Windows 10 | npm 6.4.1 | yarn 1.16.0
- elementaryOS 5.0 (ubuntu 18.04) | npm 6.9.0 | yarn 1.16.0

**Comment by jt-helsinki** [comment]
Good! When I downgraded to 1.0.2, it was ok. One thing I left out was that we are pulling from nexus, not direct from NPM. This might help explain the issue. 

I'll investigate further and if I can't find the problem I'll reopen.

Well done on this initiative. Great work!
