### ISSUE TITLE
How can these types be used in project without imports?

### ISSUE THREAD

**Issue by iFarmGolems** [hanreev/types-ol#27]
Hi,

I have a project that does not use `import` (or `require`) functionality and loads openlayers via `<script>` tag instead.

Seems like there is a mismatch in paths - e.g. `new ol.Map()` works (since Map is default-exported) but something like `ol.layer.Tile` does not work.

Is it possible to use these types on such project? 

Thanks.

**Comment by hanreev** [comment]
Hi,
unfortunately these types does not work on such project
