### ISSUE TITLE
Archive and remove from NPM

### ISSUE THREAD

**Issue by vjanssens** [hanreev/types-ol#3]
Hi,
I see [this package is merged](https://github.com/hanreev/types-ol/issues/1#issuecomment-492353542) in the official `@types/ol` library, which is great 🎉 . 
May I suggest you archive this repository and remove the package from NPM, as having these separate repositories is no longer needed anymore and can be quite confusing? Or at least have clear notice at the top of readme.md?

**Comment by hanreev** [comment]
I'll update readme.md, but i can't remove this package from npm. I've been using this package my self, and waiting PR to be merged is wasting time. definitions for openlayers 6-beta was released with this package and i have no reason to merge beta version to official `@types/ol`.
