### ISSUE TITLE
Updating @types/ol npm package is helpful

### ISSUE THREAD

**Issue by sanak** [hanreev/types-ol#33]
Hi @hanreev,

First of all, thanks for the great type definition!

I noticed your following comment on `README.md`,
> As of v6.6.0, OpenLayers has officially provided its own TypeScript definitions. Installation of third party package like **@hanreev/types-ol** or [**@types/ol**](https://www.npmjs.com/package/@types/ol) may no longer be needed.

but, at this moment, official OpenLayers type definition seems to need more fixes.
https://github.com/openlayers/openlayers/issues/13258

So, if possible, updating @types/ol npm package is helpful... 🙇‍♂️ 

I am not so familiar with TypeScript things, but if updating @types/ol is a hard work,
I will try to contribute that work as much as possible.

Best regards,

**Comment by hanreev** [comment]
@sanak Thanks for the feedback.

FYI, [the generated type definitions](https://github.com/hanreev/types-ol/tree/main/%40types/ol) are fully compatible with [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) as i am using its [toolchain](https://www.npmjs.com/package/@definitelytyped/dtslint-runner) for testing. So updating [@types/ol](https://www.npmjs.com/package/@types/ol) is not hard to do.

I will try to update [@types/ol](https://www.npmjs.com/package/@types/ol) as soon as possible. Until then, you may use @hanreev/types-ol as described [here](https://github.com/hanreev/types-ol#usage).

**Comment by sanak** [comment]
@hanreev Thanks for the advice and the PR for @types/ol ! 🙇‍♂️
