### ISSUE TITLE
generic feature

### ISSUE THREAD

**Issue by arszp10** [hanreev/types-ol#5]
code like this
```javascript
import { Feature, Collection } from 'ol';
import { Polygon } from 'ol/geom';
const features = new Collection<Feature<Polygon>>();

features.item(0).*any methods of geom/polygon* // no error
```

**Comment by hanreev** [comment]
what version of openlayers do you use?
openlayers 6 includes many generic types, unfortunately jsdoc could not parse some of them and will cause some errors when generating definition. you may use those definitions directly from js files if you want to use generic types.
