### ISSUE TITLE
overlay

### ISSUE THREAD

**Issue by arszp10** [hanreev/types-ol#6]
problem with methon setPosition in Overlay
[this repository](https://github.com/hanreev/types-ol/blob/37efc7010b5f83a1c075b750d948ad88b75a393a/%40types/ol/Overlay.d.ts#L61)

[openlayers](https://github.com/openlayers/openlayers/blob/v5.3.0/src/ol/Overlay.js#L385)

param also accept undefined

**Comment by hanreev** [comment]
Just cast `undefined` as any
```ts
overlayObject.setPosition(undefined as any);
```

**Comment by hanreev** [comment]
Fixed in v2.0.7
c5908fa3eeed1c600b2b117a016b9e37f493ceb1
