### ISSUE TITLE
Update openlayers Feature, VectorLayer to match documentation for get/setStyle, getStyleFunction

### ISSUE THREAD

**Issue by sheuertz** [hanreev/types-ol#7]
For the Feature and VectorLayer classes, the style_ property allows null to be set. Based on the documentation and the examples, a null style prevents the features from being drawn. We are trying to be able to prevent the features from being drawn while not removing them from the map.

Additionally, when setStyle is passed null, the StyleFunction of the feature is set to undefined. The getStyleFunction does not currently support undefined as a return value.

Current Definitions:
Feature.setStyle(style: StyleLike): void
Feature.getStyle(): StyleLike
Feature.getStyleFunction(): StyleFunction
VectorLayer.setStyle(style: StyleLike): void
VectorLayer.getStyle(): StyleLike
VectorLayer.getStyleFunction(): StyleFunction

Updated Definitions:
Feature.setStyle(style: StyleLike | null): void
Feature.getStyle(): StyleLike | null
Feature.getStyleFunction(): StyleFunction | undefined
VectorLayer.setStyle(style: StyleLike | null): void
VectorLayer.getStyle(): StyleLike | null
VectorLayer.getStyleFunction(): StyleFunction | undefined

Thanks!

**Comment by hanreev** [comment]
I have included `null` and `undefined` return type in this [commit](https://github.com/hanreev/types-ol/commit/3e581f38859d28509b64ccd6d19fdfa32959fd82).
AFAIK Openlayers examples never check for `null` or `undefined` return type. See [this diff and below](https://github.com/hanreev/types-ol/commit/3e581f38859d28509b64ccd6d19fdfa32959fd82#diff-0f8cbdce2aabf9a61bf20cdd2111f4d3).
> Those test files was converted from openlayers examples.

**Comment by sheuertz** [comment]
Thank you!

**Comment by hanreev** [comment]
@sheuertz [this commit](https://github.com/hanreev/types-ol/commit/5771ef312a5ffefd1e02b0c009c09eff13a50ff9) fixes `setStyle` and `getStyle`.
I'll update the [@types/ol](https://www.npmjs.com/package/@types/ol) package with those fixes while maintaining my own package ([@hanreev/types-ol](https://www.npmjs.com/package/@hanreev/types-ol)) without it.

cc: @mogoh

**Comment by hanreev** [comment]
PR created DefinitelyTyped/DefinitelyTyped#37600

**Comment by sheuertz** [comment]
Thanks so much!
